name: Daily Currency Rates Scraper
on:
  schedule:
    - cron: '0 */3 * * *'  # Runs at 13:00 UTC every day
  workflow_dispatch:     # Allows manual triggering

jobs:
  scrape-currency-rates:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # This grants write access to the repository
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GitHub token
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas playwright asyncio

        
    - name: Install Playwright browsers
      run: |
        python -m playwright install
        python -m playwright install-deps
    
    - name: Scrape Currency Rates
      run: python currency_scraper.py
    
    - name: Commit and Push Changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add logs/currency_rates.csv
        git commit -m "Update currency rates $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
